# This rule is not used by the project ollama-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ollama.smithforge.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ollama-operator
    app.kubernetes.io/managed-by: kustomize
  name: ollamamodel-admin-role
rules:
- apiGroups:
  - ollama.smithforge.dev
  resources:
  - ollamamodels
  verbs:
  - '*'
- apiGroups:
  - ollama.smithforge.dev
  resources:
  - ollamamodels/status
  verbs:
  - get
