---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ollama.smithforge.dev
  resources:
  - ollamamodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ollama.smithforge.dev
  resources:
  - ollamamodels/finalizers
  verbs:
  - update
- apiGroups:
  - ollama.smithforge.dev
  resources:
  - ollamamodels/status
  verbs:
  - get
  - patch
  - update
