# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "rack"
gem "puma"
gem "k8s-ruby"
gem "hashie"
gem "json"
gem "dotenv"

group :development, :test do
  gem "rspec"
  gem "rack-test"
  gem "pry"
end

gem "rackup", "~> 2.2"
